2025-04-14 15:00:03,340 - cephci - log:161 - DEBUG - Completed log configuration
2025-04-14 15:00:03,343 - cephci - run:722 - INFO - Running test cephfs_nfs.subvolume_export.py
2025-04-14 15:00:03,343 - cephci - subvolume_export:40 - INFO - Running cephfs CEPH-83574024 test case
2025-04-14 15:00:03,345 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.251
2025-04-14 15:00:04,349 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 15:00:04,879 - cephci - ceph:1186 - DEBUG - 
2025-04-14 15:00:04,880 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 15:00:04,880 - cephci - ceph:1186 - DEBUG - 
2025-04-14 15:00:05,732 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 1:24:11 ago on Mon Apr 14 13:35:33 2025.
2025-04-14 15:00:05,970 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 15:00:05,971 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 15:00:05,972 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 15:00:05,973 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 15:00:05,974 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 15:00:05,976 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 15:00:05,977 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 15:00:05,978 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 15:00:05,979 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 15:00:05,981 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 15:00:06,076 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 15:00:06,077 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 15:00:06,077 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 15:00:06,218 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.251 took 2.873168 seconds
2025-04-14 15:00:06,260 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.251
2025-04-14 15:00:07,264 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 15:00:07,265 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 15:00:07,265 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 15:00:07,265 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 15:00:07,265 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 15:00:07,265 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 15:00:07,265 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.251 took 1.00447 seconds
2025-04-14 15:00:07,266 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.251
2025-04-14 15:00:08,270 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.251 took 1.003826 seconds
2025-04-14 15:00:08,272 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.251
2025-04-14 15:00:09,277 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.251 took 1.003718 seconds
2025-04-14 15:00:09,279 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.3
2025-04-14 15:00:10,283 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 15:00:10,805 - cephci - ceph:1186 - DEBUG - 
2025-04-14 15:00:10,805 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 15:00:10,805 - cephci - ceph:1186 - DEBUG - 
2025-04-14 15:00:11,665 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 1:03:45 ago on Mon Apr 14 13:56:06 2025.
2025-04-14 15:00:11,898 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 15:00:11,899 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 15:00:11,900 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 15:00:11,901 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 15:00:11,902 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 15:00:11,903 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 15:00:11,905 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 15:00:11,906 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 15:00:11,907 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 15:00:11,908 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 15:00:12,001 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 15:00:12,001 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 15:00:12,002 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 15:00:12,112 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.3 took 2.832402 seconds
2025-04-14 15:00:12,154 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.3
2025-04-14 15:00:13,158 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 15:00:13,158 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 15:00:13,159 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 15:00:13,159 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 15:00:13,159 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 15:00:13,159 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 15:00:13,159 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.3 took 1.004981 seconds
2025-04-14 15:00:13,161 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.3
2025-04-14 15:00:14,165 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.3 took 1.00341 seconds
2025-04-14 15:00:14,166 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.3
2025-04-14 15:00:15,170 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.3 took 1.003545 seconds
2025-04-14 15:00:15,172 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.202
2025-04-14 15:00:16,177 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 15:00:16,754 - cephci - ceph:1186 - DEBUG - 
2025-04-14 15:00:16,755 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 15:00:16,755 - cephci - ceph:1186 - DEBUG - 
2025-04-14 15:00:17,519 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 1:20:38 ago on Mon Apr 14 13:39:18 2025.
2025-04-14 15:00:17,751 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 15:00:17,752 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 15:00:17,753 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 15:00:17,755 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 15:00:17,756 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 15:00:17,757 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 15:00:17,758 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 15:00:17,759 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 15:00:17,760 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 15:00:17,762 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 15:00:17,854 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 15:00:17,855 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 15:00:17,855 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 15:00:18,003 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.202 took 2.831165 seconds
2025-04-14 15:00:18,045 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.202
2025-04-14 15:00:19,049 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 15:00:19,049 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 15:00:19,050 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 15:00:19,050 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 15:00:19,050 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 15:00:19,050 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 15:00:19,050 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.202 took 1.004531 seconds
2025-04-14 15:00:19,052 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.202
2025-04-14 15:00:20,055 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.202 took 1.003517 seconds
2025-04-14 15:00:20,057 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.202
2025-04-14 15:00:21,061 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.202 took 1.003465 seconds
2025-04-14 15:00:21,064 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.142
2025-04-14 15:00:22,070 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 15:00:22,797 - cephci - ceph:1186 - DEBUG - 
2025-04-14 15:00:22,797 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 15:00:22,797 - cephci - ceph:1186 - DEBUG - 
2025-04-14 15:00:23,590 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 1:17:57 ago on Mon Apr 14 13:42:05 2025.
2025-04-14 15:00:23,826 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 15:00:23,828 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 15:00:23,829 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 15:00:23,831 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 15:00:23,832 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 15:00:23,833 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 15:00:23,835 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 15:00:23,836 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 15:00:23,838 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 15:00:23,839 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 15:00:23,936 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 15:00:23,937 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 15:00:23,937 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 15:00:24,112 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.142 took 3.047257 seconds
2025-04-14 15:00:24,154 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.142
2025-04-14 15:00:25,158 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 15:00:25,158 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 15:00:25,158 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 15:00:25,158 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 15:00:25,158 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 15:00:25,159 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 15:00:25,159 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.142 took 1.00445 seconds
2025-04-14 15:00:25,160 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.142
2025-04-14 15:00:26,164 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.142 took 1.003702 seconds
2025-04-14 15:00:26,166 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.142
2025-04-14 15:00:27,171 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.142 took 1.003772 seconds
2025-04-14 15:00:27,172 - cephci - ceph:1576 - INFO - Execute ceph fs ls --format json-pretty on 10.0.195.251
2025-04-14 15:00:28,176 - cephci - ceph:1606 - INFO - Execution of ceph fs ls --format json-pretty on 10.0.195.251 took 1.00318 seconds
2025-04-14 15:00:28,176 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 15:00:28,177 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251
2025-04-14 15:00:29,181 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251 took 1.003462 seconds
2025-04-14 15:00:29,183 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251
2025-04-14 15:00:30,187 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251 took 1.003456 seconds
2025-04-14 15:00:30,188 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node8 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251
2025-04-14 15:00:31,191 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node8 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251 took 1.002404 seconds
2025-04-14 15:00:31,193 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251
2025-04-14 15:00:32,196 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251 took 1.003148 seconds
2025-04-14 15:00:32,197 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 15:00:32,198 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3
2025-04-14 15:00:33,202 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3 took 1.003642 seconds
2025-04-14 15:00:33,203 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3
2025-04-14 15:00:34,207 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3 took 1.003368 seconds
2025-04-14 15:00:34,208 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node9 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3
2025-04-14 15:00:35,212 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node9 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3 took 1.003228 seconds
2025-04-14 15:00:35,213 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3
2025-04-14 15:00:36,217 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3 took 1.003382 seconds
2025-04-14 15:00:36,217 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 15:00:36,219 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202
2025-04-14 15:00:37,223 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202 took 1.003723 seconds
2025-04-14 15:00:37,224 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202
2025-04-14 15:00:38,227 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202 took 1.00312 seconds
2025-04-14 15:00:38,229 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node10 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202
2025-04-14 15:00:39,233 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node10 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202 took 1.003464 seconds
2025-04-14 15:00:39,234 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202
2025-04-14 15:00:40,238 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202 took 1.003475 seconds
2025-04-14 15:00:40,238 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 15:00:40,246 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142
2025-04-14 15:00:41,250 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142 took 1.003117 seconds
2025-04-14 15:00:41,252 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142
2025-04-14 15:00:42,256 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142 took 1.00354 seconds
2025-04-14 15:00:42,257 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node11 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142
2025-04-14 15:00:43,262 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node11 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142 took 1.004076 seconds
2025-04-14 15:00:43,263 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142
2025-04-14 15:00:44,267 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142 took 1.003466 seconds
2025-04-14 15:00:44,270 - cephci - ceph:1576 - INFO - Execute ceph nfs cluster create cephfs-nfs ceph-regression-vhr823-futhjo-node7 on 10.0.195.251
2025-04-14 15:00:45,274 - cephci - ceph:1606 - INFO - Execution of ceph nfs cluster create cephfs-nfs ceph-regression-vhr823-futhjo-node7 on 10.0.195.251 took 1.003477 seconds
2025-04-14 15:00:45,275 - cephci - cephfs_volume_management:23 - INFO - Wait for the process to start or stop
2025-04-14 15:00:45,277 - cephci - ceph:1576 - INFO - Execute ceph orch ps | grep cephfs-nfs on 10.0.195.251
2025-04-14 15:00:46,280 - cephci - ceph:1606 - INFO - Execution of ceph orch ps | grep cephfs-nfs on 10.0.195.251 took 1.003353 seconds
2025-04-14 15:00:46,282 - cephci - ceph:1576 - INFO - Execute ceph nfs cluster ls -f json on 10.0.195.251
2025-04-14 15:00:47,286 - cephci - ceph:1606 - INFO - Execution of ceph nfs cluster ls -f json on 10.0.195.251 took 1.003263 seconds
2025-04-14 15:00:47,286 - cephci - subvolume_export:73 - INFO - ceph nfs cluster created successfully
2025-04-14 15:00:47,287 - cephci - ceph:1576 - INFO - Execute ceph fs ls --format json-pretty on 10.0.195.251
2025-04-14 15:00:48,291 - cephci - ceph:1606 - INFO - Execution of ceph fs ls --format json-pretty on 10.0.195.251 took 1.003362 seconds
2025-04-14 15:00:48,293 - cephci - ceph:1576 - INFO - Execute ceph fs subvolume create cephfs subvol_nfs_1 on 10.0.195.251
2025-04-14 15:00:50,296 - cephci - ceph:1606 - INFO - Execution of ceph fs subvolume create cephfs subvol_nfs_1 on 10.0.195.251 took 2.003475 seconds
2025-04-14 15:00:50,298 - cephci - ceph:1576 - INFO - Execute ceph fs subvolumegroup create cephfs subvol_group_nfs_1 on 10.0.195.251
2025-04-14 15:00:51,302 - cephci - ceph:1606 - INFO - Execution of ceph fs subvolumegroup create cephfs subvol_group_nfs_1 on 10.0.195.251 took 1.003142 seconds
2025-04-14 15:00:51,303 - cephci - ceph:1576 - INFO - Execute ceph fs subvolume create cephfs subvol_nfs_2 subvol_group_nfs_1 on 10.0.195.251
2025-04-14 15:00:52,308 - cephci - ceph:1606 - INFO - Execution of ceph fs subvolume create cephfs subvol_nfs_2 subvol_group_nfs_1 on 10.0.195.251 took 1.003874 seconds
2025-04-14 15:00:52,310 - cephci - ceph:1576 - INFO - Execute ceph fs subvolume getpath cephfs subvol_nfs_1 on 10.0.195.251
2025-04-14 15:00:53,314 - cephci - ceph:1606 - INFO - Execution of ceph fs subvolume getpath cephfs subvol_nfs_1 on 10.0.195.251 took 1.003729 seconds
2025-04-14 15:00:53,316 - cephci - ceph:1576 - INFO - Execute ceph fs subvolume getpath cephfs subvol_nfs_2 subvol_group_nfs_1 on 10.0.195.251
2025-04-14 15:00:54,321 - cephci - ceph:1606 - INFO - Execution of ceph fs subvolume getpath cephfs subvol_nfs_2 subvol_group_nfs_1 on 10.0.195.251 took 1.004127 seconds
2025-04-14 15:00:54,323 - cephci - ceph:1576 - INFO - Execute ceph nfs export create cephfs cephfs-nfs /export_498 cephfs path=/volumes/_nogroup/subvol_nfs_1/f98487f8-812b-4554-99d4-c9ad0a33712e
 on 10.0.195.251
2025-04-14 15:00:56,327 - cephci - ceph:1606 - INFO - Execution of ceph nfs export create cephfs cephfs-nfs /export_498 cephfs path=/volumes/_nogroup/subvol_nfs_1/f98487f8-812b-4554-99d4-c9ad0a33712e
 on 10.0.195.251 took 2.003918 seconds
2025-04-14 15:00:56,329 - cephci - ceph:1576 - INFO - Execute ceph nfs export create cephfs cephfs-nfs /export_637 cephfs path=/volumes/subvol_group_nfs_1/subvol_nfs_2/800d1686-2cc2-4e31-96d7-dc6043feafb3
 on 10.0.195.251
2025-04-14 15:00:57,334 - cephci - ceph:1606 - INFO - Execution of ceph nfs export create cephfs cephfs-nfs /export_637 cephfs path=/volumes/subvol_group_nfs_1/subvol_nfs_2/800d1686-2cc2-4e31-96d7-dc6043feafb3
 on 10.0.195.251 took 1.003805 seconds
2025-04-14 15:00:57,336 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_ZSDN9 on 10.0.195.251
2025-04-14 15:00:58,340 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_ZSDN9 on 10.0.195.251 took 1.003709 seconds
2025-04-14 15:00:58,342 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_498 /mnt/nfs_ZSDN9 on 10.0.195.251
2025-04-14 15:03:03,479 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_498 /mnt/nfs_ZSDN9 on 10.0.195.251 took 125.137314 seconds
2025-04-14 15:03:03,480 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_498 /mnt/nfs_ZSDN9 returned mount.nfs: Connection refused
 and code 32 on 10.0.195.251, Retrying in 60 seconds...
2025-04-14 15:04:03,542 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_ZSDN9 on 10.0.195.251
2025-04-14 15:04:04,547 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_ZSDN9 on 10.0.195.251 took 1.003822 seconds
2025-04-14 15:04:04,548 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_498 /mnt/nfs_ZSDN9 on 10.0.195.251
2025-04-14 15:06:09,682 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_498 /mnt/nfs_ZSDN9 on 10.0.195.251 took 125.133619 seconds
2025-04-14 15:06:09,683 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_498 /mnt/nfs_ZSDN9 returned mount.nfs: Connection refused
 and code 32 on 10.0.195.251, Retrying in 120 seconds...
2025-04-14 15:08:09,783 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_ZSDN9 on 10.0.195.251
2025-04-14 15:08:10,786 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_ZSDN9 on 10.0.195.251 took 1.003202 seconds
2025-04-14 15:08:10,788 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_498 /mnt/nfs_ZSDN9 on 10.0.195.251
2025-04-14 15:10:15,922 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_498 /mnt/nfs_ZSDN9 on 10.0.195.251 took 125.133985 seconds
2025-04-14 15:10:15,923 - cephci - subvolume_export:145 - ERROR - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_498 /mnt/nfs_ZSDN9 returned mount.nfs: Connection refused
 and code 32 on 10.0.195.251
2025-04-14 15:10:15,924 - cephci - subvolume_export:146 - ERROR - Traceback (most recent call last):
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_nfs/subvolume_export.py", line 132, in run
    rc = fs_util.cephfs_nfs_mount(client1, nfs_server, nfs_export_1, nfs_mount_1)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/utility/retry.py", line 32, in f_retry
    return f(*args, **kwargs)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_utilsV1.py", line 3277, in cephfs_nfs_mount
    client.exec_command(sudo=True, cmd=command)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 2305, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 1700, in exec_command
    raise CommandFailed(
ceph.ceph.CommandFailed: mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_498 /mnt/nfs_ZSDN9 returned mount.nfs: Connection refused
 and code 32 on 10.0.195.251

2025-04-14 15:10:15,924 - cephci - subvolume_export:149 - INFO - Cleaning up
2025-04-14 15:10:15,926 - cephci - ceph:1576 - INFO - Execute rm -rf /mnt/nfs_ZSDN9/* on 10.0.195.251
2025-04-14 15:10:16,929 - cephci - ceph:1606 - INFO - Execution of rm -rf /mnt/nfs_ZSDN9/* on 10.0.195.251 took 1.003273 seconds
2025-04-14 15:10:16,931 - cephci - ceph:1576 - INFO - Execute umount /mnt/nfs_ZSDN9 on 10.0.195.251
2025-04-14 15:10:17,934 - cephci - ceph:1606 - INFO - Execution of umount /mnt/nfs_ZSDN9 on 10.0.195.251 took 1.003286 seconds
2025-04-14 15:10:17,935 - cephci - run:854 - ERROR - umount /mnt/nfs_ZSDN9 returned umount: /mnt/nfs_ZSDN9: not mounted.
 and code 32 on 10.0.195.251
Traceback (most recent call last):
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/run.py", line 839, in run
    rc = test_mod.run(
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_nfs/subvolume_export.py", line 151, in run
    client1.exec_command(sudo=True, cmd=f"umount {nfs_mount_1}")
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 2305, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 1700, in exec_command
    raise CommandFailed(
ceph.ceph.CommandFailed: umount /mnt/nfs_ZSDN9 returned umount: /mnt/nfs_ZSDN9: not mounted.
 and code 32 on 10.0.195.251
2025-04-14 15:10:17,936 - cephci - ceph:1576 - INFO - Execute podman --version | awk {'print $3'} on 10.0.195.21
2025-04-14 15:10:18,941 - cephci - ceph:1606 - INFO - Execution of podman --version | awk {'print $3'} on 10.0.195.21 took 1.003797 seconds
2025-04-14 15:10:18,941 - cephci - run:1065 - INFO - Podman Version 5.2.2
2025-04-14 15:10:18,943 - cephci - ceph:1576 - INFO - Execute docker --version | awk {'print $3'} on 10.0.195.21
2025-04-14 15:10:19,948 - cephci - ceph:1606 - INFO - Execution of docker --version | awk {'print $3'} on 10.0.195.21 took 1.00433 seconds
2025-04-14 15:10:19,949 - cephci - ceph:1576 - INFO - Execute ceph --version | awk '{print $3}' on 10.0.195.251
2025-04-14 15:10:20,953 - cephci - ceph:1606 - INFO - Execution of ceph --version | awk '{print $3}' on 10.0.195.251 took 1.003478 seconds
2025-04-14 15:10:20,954 - cephci - run:1081 - INFO - ceph Version 19.2.1-126.el9cp
2025-04-14 15:10:20,955 - cephci - run:1040 - INFO - ceph_clusters_file rerun/regression-vHr823-FUTHJO
2025-04-14 15:10:20,955 - cephci - run:927 - INFO - Test <module 'cephfs_nfs.subvolume_export' from '/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_nfs/subvolume_export.py'> failed
