2025-04-14 16:13:16,063 - cephci - log:161 - DEBUG - Completed log configuration
2025-04-14 16:13:16,065 - cephci - run:722 - INFO - Running test cephfs_nfs.nfs_mount_with_fstab.py
2025-04-14 16:13:16,066 - cephci - nfs_mount_with_fstab:45 - INFO - Running cephfs CEPH-83574025 test case
2025-04-14 16:13:16,067 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.251
2025-04-14 16:13:17,071 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 16:13:17,695 - cephci - ceph:1186 - DEBUG - 
2025-04-14 16:13:17,695 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 16:13:17,695 - cephci - ceph:1186 - DEBUG - 
2025-04-14 16:13:18,542 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 2:37:24 ago on Mon Apr 14 13:35:33 2025.
2025-04-14 16:13:18,776 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:13:18,776 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 16:13:18,778 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 16:13:18,779 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 16:13:18,780 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 16:13:18,781 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 16:13:18,782 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 16:13:18,783 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:13:18,784 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 16:13:18,785 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 16:13:18,884 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 16:13:18,885 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 16:13:18,886 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 16:13:19,002 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.251 took 2.934071 seconds
2025-04-14 16:13:19,044 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.251
2025-04-14 16:13:20,049 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 16:13:20,049 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 16:13:20,049 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 16:13:20,049 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 16:13:20,049 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 16:13:20,049 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 16:13:20,050 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.251 took 1.004774 seconds
2025-04-14 16:13:20,051 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.251
2025-04-14 16:13:21,055 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.251 took 1.003316 seconds
2025-04-14 16:13:21,056 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.251
2025-04-14 16:13:22,060 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.251 took 1.003241 seconds
2025-04-14 16:13:22,061 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.3
2025-04-14 16:13:23,065 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 16:13:23,603 - cephci - ceph:1186 - DEBUG - 
2025-04-14 16:13:23,604 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 16:13:23,604 - cephci - ceph:1186 - DEBUG - 
2025-04-14 16:13:24,461 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 2:16:57 ago on Mon Apr 14 13:56:06 2025.
2025-04-14 16:13:24,718 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:13:24,718 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 16:13:24,719 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 16:13:24,721 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 16:13:24,722 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 16:13:24,723 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 16:13:24,724 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 16:13:24,725 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:13:24,728 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 16:13:24,729 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 16:13:24,830 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 16:13:24,831 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 16:13:24,832 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 16:13:24,946 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.3 took 2.884162 seconds
2025-04-14 16:13:24,988 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.3
2025-04-14 16:13:25,991 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 16:13:25,992 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 16:13:25,992 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 16:13:25,992 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 16:13:25,992 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 16:13:25,992 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 16:13:25,992 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.3 took 1.004026 seconds
2025-04-14 16:13:25,993 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.3
2025-04-14 16:13:26,997 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.3 took 1.003244 seconds
2025-04-14 16:13:26,998 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.3
2025-04-14 16:13:28,002 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.3 took 1.003164 seconds
2025-04-14 16:13:28,004 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.202
2025-04-14 16:13:29,008 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 16:13:29,570 - cephci - ceph:1186 - DEBUG - 
2025-04-14 16:13:29,570 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 16:13:29,570 - cephci - ceph:1186 - DEBUG - 
2025-04-14 16:13:30,311 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 2:33:51 ago on Mon Apr 14 13:39:18 2025.
2025-04-14 16:13:30,555 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:13:30,556 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 16:13:30,557 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 16:13:30,558 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 16:13:30,559 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 16:13:30,560 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 16:13:30,562 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 16:13:30,563 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:13:30,564 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 16:13:30,565 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 16:13:30,674 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 16:13:30,675 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 16:13:30,675 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 16:13:30,831 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.202 took 2.826725 seconds
2025-04-14 16:13:30,873 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.202
2025-04-14 16:13:31,877 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 16:13:31,877 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 16:13:31,877 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 16:13:31,877 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 16:13:31,878 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 16:13:31,878 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 16:13:31,878 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.202 took 1.0043 seconds
2025-04-14 16:13:31,879 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.202
2025-04-14 16:13:32,883 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.202 took 1.0034 seconds
2025-04-14 16:13:32,884 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.202
2025-04-14 16:13:33,887 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.202 took 1.003211 seconds
2025-04-14 16:13:33,889 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.142
2025-04-14 16:13:34,893 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 16:13:35,412 - cephci - ceph:1186 - DEBUG - 
2025-04-14 16:13:35,412 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 16:13:35,412 - cephci - ceph:1186 - DEBUG - 
2025-04-14 16:13:36,182 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 2:31:10 ago on Mon Apr 14 13:42:05 2025.
2025-04-14 16:13:36,415 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:13:36,417 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 16:13:36,417 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 16:13:36,418 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 16:13:36,419 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 16:13:36,421 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 16:13:36,422 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 16:13:36,423 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:13:36,424 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 16:13:36,425 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 16:13:36,515 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 16:13:36,516 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 16:13:36,517 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 16:13:36,667 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.142 took 2.777054 seconds
2025-04-14 16:13:36,708 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.142
2025-04-14 16:13:37,712 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 16:13:37,713 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 16:13:37,713 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 16:13:37,713 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 16:13:37,713 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 16:13:37,714 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 16:13:37,714 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.142 took 1.00493 seconds
2025-04-14 16:13:37,715 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.142
2025-04-14 16:13:38,720 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.142 took 1.003782 seconds
2025-04-14 16:13:38,722 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.142
2025-04-14 16:13:39,726 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.142 took 1.003595 seconds
2025-04-14 16:13:39,728 - cephci - ceph:1576 - INFO - Execute ceph fs ls --format json-pretty on 10.0.195.251
2025-04-14 16:13:40,732 - cephci - ceph:1606 - INFO - Execution of ceph fs ls --format json-pretty on 10.0.195.251 took 1.003389 seconds
2025-04-14 16:13:40,732 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 16:13:40,734 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251
2025-04-14 16:13:41,738 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251 took 1.003959 seconds
2025-04-14 16:13:41,740 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251
2025-04-14 16:13:42,745 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251 took 1.003827 seconds
2025-04-14 16:13:42,746 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node8 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251
2025-04-14 16:13:43,751 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node8 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251 took 1.003617 seconds
2025-04-14 16:13:43,752 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251
2025-04-14 16:13:44,756 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251 took 1.003441 seconds
2025-04-14 16:13:44,757 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 16:13:44,758 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3
2025-04-14 16:13:45,763 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3 took 1.004225 seconds
2025-04-14 16:13:45,764 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3
2025-04-14 16:13:46,768 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3 took 1.003257 seconds
2025-04-14 16:13:46,770 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node9 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3
2025-04-14 16:13:47,774 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node9 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3 took 1.003645 seconds
2025-04-14 16:13:47,776 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3
2025-04-14 16:13:48,780 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3 took 1.003433 seconds
2025-04-14 16:13:48,780 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 16:13:48,782 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202
2025-04-14 16:13:49,786 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202 took 1.003802 seconds
2025-04-14 16:13:49,788 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202
2025-04-14 16:13:50,792 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202 took 1.004147 seconds
2025-04-14 16:13:50,794 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node10 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202
2025-04-14 16:13:51,798 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node10 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202 took 1.003072 seconds
2025-04-14 16:13:51,800 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202
2025-04-14 16:13:52,805 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202 took 1.003638 seconds
2025-04-14 16:13:52,805 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 16:13:52,808 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142
2025-04-14 16:13:53,813 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142 took 1.003903 seconds
2025-04-14 16:13:53,814 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142
2025-04-14 16:13:54,818 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142 took 1.003488 seconds
2025-04-14 16:13:54,822 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node11 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142
2025-04-14 16:13:55,825 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node11 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142 took 1.003219 seconds
2025-04-14 16:13:55,827 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142
2025-04-14 16:13:56,830 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142 took 1.003097 seconds
2025-04-14 16:13:56,834 - cephci - ceph:1576 - INFO - Execute ceph nfs cluster create cephfs-nfs ceph-regression-vhr823-futhjo-node7 on 10.0.195.251
2025-04-14 16:13:57,839 - cephci - ceph:1606 - INFO - Execution of ceph nfs cluster create cephfs-nfs ceph-regression-vhr823-futhjo-node7 on 10.0.195.251 took 1.004192 seconds
2025-04-14 16:13:57,839 - cephci - cephfs_volume_management:23 - INFO - Wait for the process to start or stop
2025-04-14 16:13:57,841 - cephci - ceph:1576 - INFO - Execute ceph orch ps | grep cephfs-nfs on 10.0.195.251
2025-04-14 16:13:58,844 - cephci - ceph:1606 - INFO - Execution of ceph orch ps | grep cephfs-nfs on 10.0.195.251 took 1.003062 seconds
2025-04-14 16:13:58,846 - cephci - ceph:1576 - INFO - Execute ceph nfs cluster ls -f json on 10.0.195.251
2025-04-14 16:13:59,851 - cephci - ceph:1606 - INFO - Execution of ceph nfs cluster ls -f json on 10.0.195.251 took 1.004106 seconds
2025-04-14 16:13:59,852 - cephci - nfs_mount_with_fstab:82 - INFO - ceph nfs cluster created successfully
2025-04-14 16:13:59,853 - cephci - ceph:1576 - INFO - Execute ceph fs ls --format json-pretty on 10.0.195.251
2025-04-14 16:14:00,857 - cephci - ceph:1606 - INFO - Execution of ceph fs ls --format json-pretty on 10.0.195.251 took 1.003885 seconds
2025-04-14 16:14:00,860 - cephci - ceph:1576 - INFO - Execute ceph nfs export create cephfs cephfs-nfs /export_037 cephfs path=/ on 10.0.195.251
2025-04-14 16:14:01,864 - cephci - ceph:1606 - INFO - Execution of ceph nfs export create cephfs cephfs-nfs /export_037 cephfs path=/ on 10.0.195.251 took 1.004029 seconds
2025-04-14 16:14:01,866 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_7O903 on 10.0.195.251
2025-04-14 16:14:02,870 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_7O903 on 10.0.195.251 took 1.003831 seconds
2025-04-14 16:14:02,874 - cephci - ceph:1576 - INFO - Execute ls -lrt /etc/fstab.backup on 10.0.195.251
2025-04-14 16:14:03,878 - cephci - ceph:1606 - INFO - Execution of ls -lrt /etc/fstab.backup on 10.0.195.251 took 1.004001 seconds
2025-04-14 16:14:03,880 - cephci - ceph:1576 - INFO - Execute cp /etc/fstab /etc/fstab.backup on 10.0.195.251
2025-04-14 16:14:04,884 - cephci - ceph:1606 - INFO - Execution of cp /etc/fstab /etc/fstab.backup on 10.0.195.251 took 1.003496 seconds
2025-04-14 16:14:04,918 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_037 /mnt/nfs_7O903 on 10.0.195.251
2025-04-14 16:16:10,057 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_037 /mnt/nfs_7O903 on 10.0.195.251 took 125.139011 seconds
2025-04-14 16:16:10,058 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_037 /mnt/nfs_7O903 returned mount.nfs: Connection refused
 and code 32 on 10.0.195.251, Retrying in 60 seconds...
2025-04-14 16:17:10,106 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_7O903 on 10.0.195.251
2025-04-14 16:17:11,110 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_7O903 on 10.0.195.251 took 1.002904 seconds
2025-04-14 16:17:11,112 - cephci - ceph:1576 - INFO - Execute ls -lrt /etc/fstab.backup on 10.0.195.251
2025-04-14 16:17:12,116 - cephci - ceph:1606 - INFO - Execution of ls -lrt /etc/fstab.backup on 10.0.195.251 took 1.003995 seconds
2025-04-14 16:17:12,149 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_037 /mnt/nfs_7O903 on 10.0.195.251
2025-04-14 16:19:17,288 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_037 /mnt/nfs_7O903 on 10.0.195.251 took 125.138576 seconds
2025-04-14 16:19:17,289 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_037 /mnt/nfs_7O903 returned mount.nfs: Connection refused
 and code 32 on 10.0.195.251, Retrying in 120 seconds...
2025-04-14 16:21:17,390 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_7O903 on 10.0.195.251
2025-04-14 16:21:18,394 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_7O903 on 10.0.195.251 took 1.003006 seconds
2025-04-14 16:21:18,395 - cephci - ceph:1576 - INFO - Execute ls -lrt /etc/fstab.backup on 10.0.195.251
2025-04-14 16:21:19,399 - cephci - ceph:1606 - INFO - Execution of ls -lrt /etc/fstab.backup on 10.0.195.251 took 1.003648 seconds
2025-04-14 16:21:19,428 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_037 /mnt/nfs_7O903 on 10.0.195.251
2025-04-14 16:23:24,565 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_037 /mnt/nfs_7O903 on 10.0.195.251 took 125.13563 seconds
2025-04-14 16:23:24,565 - cephci - nfs_mount_with_fstab:135 - ERROR - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_037 /mnt/nfs_7O903 returned mount.nfs: Connection refused
 and code 32 on 10.0.195.251
2025-04-14 16:23:24,566 - cephci - nfs_mount_with_fstab:136 - ERROR - Traceback (most recent call last):
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_nfs/nfs_mount_with_fstab.py", line 106, in run
    rc = fs_util.cephfs_nfs_mount(
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/utility/retry.py", line 32, in f_retry
    return f(*args, **kwargs)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_utilsV1.py", line 3277, in cephfs_nfs_mount
    client.exec_command(sudo=True, cmd=command)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 2305, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 1700, in exec_command
    raise CommandFailed(
ceph.ceph.CommandFailed: mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_037 /mnt/nfs_7O903 returned mount.nfs: Connection refused
 and code 32 on 10.0.195.251

2025-04-14 16:23:24,567 - cephci - nfs_mount_with_fstab:139 - INFO - Cleaning up the system
2025-04-14 16:23:24,568 - cephci - ceph:1576 - INFO - Execute rm -rf /mnt/nfs_7O903/* on 10.0.195.251
2025-04-14 16:23:25,572 - cephci - ceph:1606 - INFO - Execution of rm -rf /mnt/nfs_7O903/* on 10.0.195.251 took 1.003161 seconds
2025-04-14 16:23:25,574 - cephci - ceph:1576 - INFO - Execute umount /mnt/nfs_7O903 on 10.0.195.251
2025-04-14 16:23:26,578 - cephci - ceph:1606 - INFO - Execution of umount /mnt/nfs_7O903 on 10.0.195.251 took 1.004101 seconds
2025-04-14 16:23:26,580 - cephci - run:854 - ERROR - umount /mnt/nfs_7O903 returned umount: /mnt/nfs_7O903: not mounted.
 and code 32 on 10.0.195.251
Traceback (most recent call last):
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/run.py", line 839, in run
    rc = test_mod.run(
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_nfs/nfs_mount_with_fstab.py", line 146, in run
    client1.exec_command(sudo=True, cmd=command)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 2305, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 1700, in exec_command
    raise CommandFailed(
ceph.ceph.CommandFailed: umount /mnt/nfs_7O903 returned umount: /mnt/nfs_7O903: not mounted.
 and code 32 on 10.0.195.251
2025-04-14 16:23:26,586 - cephci - ceph:1576 - INFO - Execute podman --version | awk {'print $3'} on 10.0.195.21
2025-04-14 16:23:27,591 - cephci - ceph:1606 - INFO - Execution of podman --version | awk {'print $3'} on 10.0.195.21 took 1.004632 seconds
2025-04-14 16:23:27,592 - cephci - run:1065 - INFO - Podman Version 5.2.2
2025-04-14 16:23:27,593 - cephci - ceph:1576 - INFO - Execute docker --version | awk {'print $3'} on 10.0.195.21
2025-04-14 16:23:28,598 - cephci - ceph:1606 - INFO - Execution of docker --version | awk {'print $3'} on 10.0.195.21 took 1.004023 seconds
2025-04-14 16:23:28,599 - cephci - ceph:1576 - INFO - Execute ceph --version | awk '{print $3}' on 10.0.195.251
2025-04-14 16:23:29,603 - cephci - ceph:1606 - INFO - Execution of ceph --version | awk '{print $3}' on 10.0.195.251 took 1.003378 seconds
2025-04-14 16:23:29,604 - cephci - run:1081 - INFO - ceph Version 19.2.1-126.el9cp
2025-04-14 16:23:29,605 - cephci - run:1040 - INFO - ceph_clusters_file rerun/regression-vHr823-FUTHJO
2025-04-14 16:23:29,605 - cephci - run:927 - INFO - Test <module 'cephfs_nfs.nfs_mount_with_fstab' from '/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_nfs/nfs_mount_with_fstab.py'> failed
