2025-04-14 15:59:57,636 - cephci - log:161 - DEBUG - Completed log configuration
2025-04-14 15:59:57,638 - cephci - run:722 - INFO - Running test cephfs_nfs.nfs_io_network_failures.py
2025-04-14 15:59:57,638 - cephci - nfs_io_network_failures:59 - INFO - Running cephfs CEPH-83574020 test case
2025-04-14 15:59:57,640 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.251
2025-04-14 15:59:58,644 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 15:59:59,288 - cephci - ceph:1186 - DEBUG - 
2025-04-14 15:59:59,288 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 15:59:59,288 - cephci - ceph:1186 - DEBUG - 
2025-04-14 16:00:00,118 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 2:24:06 ago on Mon Apr 14 13:35:33 2025.
2025-04-14 16:00:00,349 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:00:00,350 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 16:00:00,351 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 16:00:00,352 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 16:00:00,353 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 16:00:00,354 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 16:00:00,355 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 16:00:00,356 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:00:00,358 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 16:00:00,359 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 16:00:00,451 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 16:00:00,452 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 16:00:00,452 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 16:00:01,596 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.251 took 3.955881 seconds
2025-04-14 16:00:01,598 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.251
2025-04-14 16:00:02,602 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 16:00:02,603 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 16:00:02,603 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 16:00:02,603 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 16:00:02,603 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 16:00:02,603 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 16:00:02,603 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.251 took 1.005466 seconds
2025-04-14 16:00:02,605 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.251
2025-04-14 16:00:03,608 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.251 took 1.003537 seconds
2025-04-14 16:00:03,612 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.251
2025-04-14 16:00:04,616 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.251 took 1.003431 seconds
2025-04-14 16:00:04,619 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.3
2025-04-14 16:00:05,622 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 16:00:06,119 - cephci - ceph:1186 - DEBUG - 
2025-04-14 16:00:06,119 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 16:00:06,119 - cephci - ceph:1186 - DEBUG - 
2025-04-14 16:00:06,958 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 2:03:40 ago on Mon Apr 14 13:56:06 2025.
2025-04-14 16:00:07,196 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:00:07,197 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 16:00:07,198 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 16:00:07,199 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 16:00:07,200 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 16:00:07,202 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 16:00:07,203 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 16:00:07,204 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:00:07,205 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 16:00:07,206 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 16:00:07,299 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 16:00:07,300 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 16:00:07,300 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 16:00:07,406 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.3 took 2.78674 seconds
2025-04-14 16:00:07,447 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.3
2025-04-14 16:00:08,451 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 16:00:08,451 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 16:00:08,451 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 16:00:08,451 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 16:00:08,451 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 16:00:08,451 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 16:00:08,452 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.3 took 1.00432 seconds
2025-04-14 16:00:08,453 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.3
2025-04-14 16:00:09,456 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.3 took 1.003276 seconds
2025-04-14 16:00:09,458 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.3
2025-04-14 16:00:10,461 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.3 took 1.00328 seconds
2025-04-14 16:00:10,464 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.202
2025-04-14 16:00:11,470 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 16:00:11,955 - cephci - ceph:1186 - DEBUG - 
2025-04-14 16:00:11,956 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 16:00:11,956 - cephci - ceph:1186 - DEBUG - 
2025-04-14 16:00:12,692 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 2:20:33 ago on Mon Apr 14 13:39:18 2025.
2025-04-14 16:00:12,918 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:00:12,919 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 16:00:12,920 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 16:00:12,921 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 16:00:12,922 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 16:00:12,923 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 16:00:12,924 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 16:00:12,925 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:00:12,926 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 16:00:12,928 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 16:00:13,016 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 16:00:13,017 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 16:00:13,017 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 16:00:13,374 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.202 took 2.908886 seconds
2025-04-14 16:00:13,416 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.202
2025-04-14 16:00:14,420 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 16:00:14,420 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 16:00:14,420 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 16:00:14,420 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 16:00:14,421 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 16:00:14,421 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 16:00:14,421 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.202 took 1.004421 seconds
2025-04-14 16:00:14,422 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.202
2025-04-14 16:00:15,426 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.202 took 1.003124 seconds
2025-04-14 16:00:15,427 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.202
2025-04-14 16:00:16,431 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.202 took 1.003026 seconds
2025-04-14 16:00:16,434 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.142
2025-04-14 16:00:17,438 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 16:00:17,961 - cephci - ceph:1186 - DEBUG - 
2025-04-14 16:00:17,962 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 16:00:17,962 - cephci - ceph:1186 - DEBUG - 
2025-04-14 16:00:18,720 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 2:17:52 ago on Mon Apr 14 13:42:05 2025.
2025-04-14 16:00:18,966 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:00:18,967 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 16:00:18,968 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 16:00:18,969 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 16:00:18,970 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 16:00:18,971 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 16:00:18,972 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 16:00:18,973 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 16:00:18,975 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 16:00:18,976 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 16:00:19,067 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 16:00:19,068 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 16:00:19,068 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 16:00:20,212 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.142 took 3.777779 seconds
2025-04-14 16:00:20,214 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.142
2025-04-14 16:00:21,218 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 16:00:21,218 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 16:00:21,219 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 16:00:21,219 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 16:00:21,219 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 16:00:21,219 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 16:00:21,219 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.142 took 1.005071 seconds
2025-04-14 16:00:21,221 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.142
2025-04-14 16:00:22,225 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.142 took 1.004016 seconds
2025-04-14 16:00:22,227 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.142
2025-04-14 16:00:23,231 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.142 took 1.00374 seconds
2025-04-14 16:00:23,233 - cephci - ceph:1576 - INFO - Execute ceph fs ls --format json-pretty on 10.0.195.251
2025-04-14 16:00:24,236 - cephci - ceph:1606 - INFO - Execution of ceph fs ls --format json-pretty on 10.0.195.251 took 1.00327 seconds
2025-04-14 16:00:24,237 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 16:00:24,238 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251
2025-04-14 16:00:25,242 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251 took 1.003277 seconds
2025-04-14 16:00:25,243 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251
2025-04-14 16:00:26,246 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251 took 1.003222 seconds
2025-04-14 16:00:26,248 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node8 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251
2025-04-14 16:00:27,252 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node8 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251 took 1.003586 seconds
2025-04-14 16:00:27,254 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251
2025-04-14 16:00:28,258 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251 took 1.003433 seconds
2025-04-14 16:00:28,259 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 16:00:28,260 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3
2025-04-14 16:00:29,263 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3 took 1.003086 seconds
2025-04-14 16:00:29,264 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3
2025-04-14 16:00:30,267 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3 took 1.002885 seconds
2025-04-14 16:00:30,269 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node9 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3
2025-04-14 16:00:31,273 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node9 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3 took 1.003488 seconds
2025-04-14 16:00:31,275 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3
2025-04-14 16:00:32,279 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3 took 1.003487 seconds
2025-04-14 16:00:32,279 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 16:00:32,281 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202
2025-04-14 16:00:33,284 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202 took 1.003161 seconds
2025-04-14 16:00:33,286 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202
2025-04-14 16:00:34,289 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202 took 1.003051 seconds
2025-04-14 16:00:34,291 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node10 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202
2025-04-14 16:00:35,295 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node10 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202 took 1.003149 seconds
2025-04-14 16:00:35,297 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202
2025-04-14 16:00:36,301 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202 took 1.003395 seconds
2025-04-14 16:00:36,301 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 16:00:36,304 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142
2025-04-14 16:00:37,309 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142 took 1.004221 seconds
2025-04-14 16:00:37,311 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142
2025-04-14 16:00:38,314 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142 took 1.002623 seconds
2025-04-14 16:00:38,316 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node11 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142
2025-04-14 16:00:39,321 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node11 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142 took 1.003737 seconds
2025-04-14 16:00:39,324 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142
2025-04-14 16:00:40,328 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142 took 1.003248 seconds
2025-04-14 16:00:40,331 - cephci - ceph:1576 - INFO - Execute ceph nfs cluster create cephfs-nfs ceph-regression-vhr823-futhjo-node7 on 10.0.195.251
2025-04-14 16:00:41,336 - cephci - ceph:1606 - INFO - Execution of ceph nfs cluster create cephfs-nfs ceph-regression-vhr823-futhjo-node7 on 10.0.195.251 took 1.003878 seconds
2025-04-14 16:00:41,336 - cephci - cephfs_volume_management:23 - INFO - Wait for the process to start or stop
2025-04-14 16:00:41,338 - cephci - ceph:1576 - INFO - Execute ceph orch ps | grep cephfs-nfs on 10.0.195.251
2025-04-14 16:00:42,342 - cephci - ceph:1606 - INFO - Execution of ceph orch ps | grep cephfs-nfs on 10.0.195.251 took 1.003534 seconds
2025-04-14 16:00:47,345 - cephci - ceph:1576 - INFO - Execute ceph orch ps | grep cephfs-nfs on 10.0.195.251
2025-04-14 16:00:48,349 - cephci - ceph:1606 - INFO - Execution of ceph orch ps | grep cephfs-nfs on 10.0.195.251 took 1.003539 seconds
2025-04-14 16:00:48,351 - cephci - ceph:1576 - INFO - Execute ceph nfs cluster ls -f json on 10.0.195.251
2025-04-14 16:00:49,355 - cephci - ceph:1606 - INFO - Execution of ceph nfs cluster ls -f json on 10.0.195.251 took 1.003674 seconds
2025-04-14 16:00:49,356 - cephci - nfs_io_network_failures:30 - INFO - ceph nfs cluster created successfully
2025-04-14 16:00:49,358 - cephci - ceph:1576 - INFO - Execute ceph fs ls --format json-pretty on 10.0.195.251
2025-04-14 16:00:50,362 - cephci - ceph:1606 - INFO - Execution of ceph fs ls --format json-pretty on 10.0.195.251 took 1.003782 seconds
2025-04-14 16:00:50,364 - cephci - ceph:1576 - INFO - Execute ceph nfs export create cephfs cephfs-nfs /export_366 cephfs path=/ on 10.0.195.251
2025-04-14 16:00:52,369 - cephci - ceph:1606 - INFO - Execution of ceph nfs export create cephfs cephfs-nfs /export_366 cephfs path=/ on 10.0.195.251 took 2.004775 seconds
2025-04-14 16:00:52,371 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:00:53,375 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_AJCCI on 10.0.195.251 took 1.003746 seconds
2025-04-14 16:00:53,377 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:00:54,381 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251 took 1.00327 seconds
2025-04-14 16:00:54,381 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI returned mount.nfs: access denied by server while mounting ceph-regression-vhr823-futhjo-node7:/export_366
 and code 32 on 10.0.195.251, Retrying in 60 seconds...
2025-04-14 16:01:54,443 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:01:55,447 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_AJCCI on 10.0.195.251 took 1.003919 seconds
2025-04-14 16:01:55,449 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:01:56,454 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251 took 1.003426 seconds
2025-04-14 16:01:56,454 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI returned mount.nfs: access denied by server while mounting ceph-regression-vhr823-futhjo-node7:/export_366
 and code 32 on 10.0.195.251, Retrying in 120 seconds...
2025-04-14 16:03:56,543 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:03:57,547 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_AJCCI on 10.0.195.251 took 1.003304 seconds
2025-04-14 16:03:57,548 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:03:58,552 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251 took 1.003415 seconds
2025-04-14 16:03:58,553 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI returned mount.nfs: access denied by server while mounting ceph-regression-vhr823-futhjo-node7:/export_366
 and code 32 on 10.0.195.251, Retrying in 60 seconds...
2025-04-14 16:04:58,588 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:04:59,592 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_AJCCI on 10.0.195.251 took 1.003146 seconds
2025-04-14 16:04:59,594 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:05:00,599 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251 took 1.004083 seconds
2025-04-14 16:05:00,600 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI returned mount.nfs: access denied by server while mounting ceph-regression-vhr823-futhjo-node7:/export_366
 and code 32 on 10.0.195.251, Retrying in 60 seconds...
2025-04-14 16:06:00,638 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:06:01,641 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_AJCCI on 10.0.195.251 took 1.003347 seconds
2025-04-14 16:06:01,643 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:06:02,647 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251 took 1.0035 seconds
2025-04-14 16:06:02,648 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI returned mount.nfs: access denied by server while mounting ceph-regression-vhr823-futhjo-node7:/export_366
 and code 32 on 10.0.195.251, Retrying in 120 seconds...
2025-04-14 16:08:02,748 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:08:03,753 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_AJCCI on 10.0.195.251 took 1.003634 seconds
2025-04-14 16:08:03,755 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:08:04,759 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251 took 1.003487 seconds
2025-04-14 16:08:04,759 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI returned mount.nfs: access denied by server while mounting ceph-regression-vhr823-futhjo-node7:/export_366
 and code 32 on 10.0.195.251, Retrying in 120 seconds...
2025-04-14 16:10:04,856 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:10:05,860 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_AJCCI on 10.0.195.251 took 1.003459 seconds
2025-04-14 16:10:05,862 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:10:06,866 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251 took 1.003395 seconds
2025-04-14 16:10:06,867 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI returned mount.nfs: access denied by server while mounting ceph-regression-vhr823-futhjo-node7:/export_366
 and code 32 on 10.0.195.251, Retrying in 60 seconds...
2025-04-14 16:11:06,920 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:11:07,925 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_AJCCI on 10.0.195.251 took 1.003471 seconds
2025-04-14 16:11:07,927 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:11:08,931 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251 took 1.003719 seconds
2025-04-14 16:11:08,932 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI returned mount.nfs: access denied by server while mounting ceph-regression-vhr823-futhjo-node7:/export_366
 and code 32 on 10.0.195.251, Retrying in 120 seconds...
2025-04-14 16:13:09,021 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:13:10,025 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_AJCCI on 10.0.195.251 took 1.003835 seconds
2025-04-14 16:13:10,027 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:13:11,031 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI on 10.0.195.251 took 1.003588 seconds
2025-04-14 16:13:11,031 - cephci - nfs_io_network_failures:139 - ERROR - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI returned mount.nfs: access denied by server while mounting ceph-regression-vhr823-futhjo-node7:/export_366
 and code 32 on 10.0.195.251
2025-04-14 16:13:11,032 - cephci - nfs_io_network_failures:140 - ERROR - Traceback (most recent call last):
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_nfs/nfs_io_network_failures.py", line 114, in run
    rc = retry_mount(client1, nfs_server, nfs_export_name, nfs_mounting_dir)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/utility/retry.py", line 32, in f_retry
    return f(*args, **kwargs)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/utility/retry.py", line 32, in f_retry
    return f(*args, **kwargs)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_utilsV1.py", line 3277, in cephfs_nfs_mount
    client.exec_command(sudo=True, cmd=command)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 2305, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 1700, in exec_command
    raise CommandFailed(
ceph.ceph.CommandFailed: mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_366 /mnt/nfs_AJCCI returned mount.nfs: access denied by server while mounting ceph-regression-vhr823-futhjo-node7:/export_366
 and code 32 on 10.0.195.251

2025-04-14 16:13:11,032 - cephci - nfs_io_network_failures:143 - INFO - Cleaning up the system
2025-04-14 16:13:11,034 - cephci - ceph:1576 - INFO - Execute rm -rf /mnt/nfs_AJCCI/* on 10.0.195.251
2025-04-14 16:13:12,037 - cephci - ceph:1606 - INFO - Execution of rm -rf /mnt/nfs_AJCCI/* on 10.0.195.251 took 1.003661 seconds
2025-04-14 16:13:12,039 - cephci - ceph:1576 - INFO - Execute umount /mnt/nfs_AJCCI on 10.0.195.251
2025-04-14 16:13:13,042 - cephci - ceph:1606 - INFO - Execution of umount /mnt/nfs_AJCCI on 10.0.195.251 took 1.003157 seconds
2025-04-14 16:13:13,043 - cephci - run:854 - ERROR - umount /mnt/nfs_AJCCI returned umount: /mnt/nfs_AJCCI: not mounted.
 and code 32 on 10.0.195.251
Traceback (most recent call last):
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/run.py", line 839, in run
    rc = test_mod.run(
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_nfs/nfs_io_network_failures.py", line 150, in run
    client1.exec_command(sudo=True, cmd=command)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 2305, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 1700, in exec_command
    raise CommandFailed(
ceph.ceph.CommandFailed: umount /mnt/nfs_AJCCI returned umount: /mnt/nfs_AJCCI: not mounted.
 and code 32 on 10.0.195.251
2025-04-14 16:13:13,045 - cephci - ceph:1576 - INFO - Execute podman --version | awk {'print $3'} on 10.0.195.21
2025-04-14 16:13:14,049 - cephci - ceph:1606 - INFO - Execution of podman --version | awk {'print $3'} on 10.0.195.21 took 1.00368 seconds
2025-04-14 16:13:14,049 - cephci - run:1065 - INFO - Podman Version 5.2.2
2025-04-14 16:13:14,050 - cephci - ceph:1576 - INFO - Execute docker --version | awk {'print $3'} on 10.0.195.21
2025-04-14 16:13:15,055 - cephci - ceph:1606 - INFO - Execution of docker --version | awk {'print $3'} on 10.0.195.21 took 1.004369 seconds
2025-04-14 16:13:15,056 - cephci - ceph:1576 - INFO - Execute ceph --version | awk '{print $3}' on 10.0.195.251
2025-04-14 16:13:16,060 - cephci - ceph:1606 - INFO - Execution of ceph --version | awk '{print $3}' on 10.0.195.251 took 1.003339 seconds
2025-04-14 16:13:16,061 - cephci - run:1081 - INFO - ceph Version 19.2.1-126.el9cp
2025-04-14 16:13:16,062 - cephci - run:1040 - INFO - ceph_clusters_file rerun/regression-vHr823-FUTHJO
2025-04-14 16:13:16,062 - cephci - run:927 - INFO - Test <module 'cephfs_nfs.nfs_io_network_failures' from '/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_nfs/nfs_io_network_failures.py'> failed
