2025-04-14 14:49:52,408 - cephci - log:161 - DEBUG - Completed log configuration
2025-04-14 14:49:52,411 - cephci - run:722 - INFO - Running test cephfs_nfs.zip_unzip_files_nfs.py
2025-04-14 14:49:52,411 - cephci - zip_unzip_files_nfs:36 - INFO - Running cephfs CEPH-83574024 test case
2025-04-14 14:49:52,412 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.251
2025-04-14 14:49:53,416 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 14:49:53,916 - cephci - ceph:1186 - DEBUG - 
2025-04-14 14:49:53,916 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 14:49:53,916 - cephci - ceph:1186 - DEBUG - 
2025-04-14 14:49:54,739 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 1:14:00 ago on Mon Apr 14 13:35:33 2025.
2025-04-14 14:49:54,992 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 14:49:54,993 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 14:49:54,994 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 14:49:54,995 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 14:49:54,996 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 14:49:54,997 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 14:49:54,998 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 14:49:54,999 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 14:49:55,000 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 14:49:55,001 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 14:49:55,094 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 14:49:55,095 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 14:49:55,095 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 14:49:55,255 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.251 took 2.842141 seconds
2025-04-14 14:49:55,297 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.251
2025-04-14 14:49:56,300 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 14:49:56,301 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 14:49:56,301 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 14:49:56,301 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 14:49:56,301 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 14:49:56,301 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 14:49:56,301 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.251 took 1.004308 seconds
2025-04-14 14:49:56,303 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.251
2025-04-14 14:49:57,307 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.251 took 1.003241 seconds
2025-04-14 14:49:57,308 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.251
2025-04-14 14:49:58,311 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.251 took 1.002956 seconds
2025-04-14 14:49:58,317 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.3
2025-04-14 14:49:59,325 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 14:49:59,886 - cephci - ceph:1186 - DEBUG - 
2025-04-14 14:49:59,887 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 14:49:59,887 - cephci - ceph:1186 - DEBUG - 
2025-04-14 14:50:00,773 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 0:53:34 ago on Mon Apr 14 13:56:06 2025.
2025-04-14 14:50:01,010 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 14:50:01,011 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 14:50:01,013 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 14:50:01,014 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 14:50:01,015 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 14:50:01,016 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 14:50:01,017 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 14:50:01,018 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 14:50:01,020 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 14:50:01,021 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 14:50:01,115 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 14:50:01,116 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 14:50:01,116 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 14:50:01,276 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.3 took 2.95866 seconds
2025-04-14 14:50:01,318 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.3
2025-04-14 14:50:02,322 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 14:50:02,323 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 14:50:02,323 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 14:50:02,323 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 14:50:02,323 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 14:50:02,323 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 14:50:02,324 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.3 took 1.004774 seconds
2025-04-14 14:50:02,325 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.3
2025-04-14 14:50:03,329 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.3 took 1.00334 seconds
2025-04-14 14:50:03,330 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.3
2025-04-14 14:50:04,334 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.3 took 1.003101 seconds
2025-04-14 14:50:04,337 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.202
2025-04-14 14:50:05,347 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 14:50:05,957 - cephci - ceph:1186 - DEBUG - 
2025-04-14 14:50:05,958 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 14:50:05,958 - cephci - ceph:1186 - DEBUG - 
2025-04-14 14:50:06,792 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 1:10:27 ago on Mon Apr 14 13:39:18 2025.
2025-04-14 14:50:07,031 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 14:50:07,032 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 14:50:07,033 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 14:50:07,034 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 14:50:07,035 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 14:50:07,036 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 14:50:07,037 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 14:50:07,038 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 14:50:07,039 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 14:50:07,040 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 14:50:07,132 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 14:50:07,133 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 14:50:07,133 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 14:50:07,359 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.202 took 3.02196 seconds
2025-04-14 14:50:07,401 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.202
2025-04-14 14:50:08,405 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 14:50:08,405 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 14:50:08,406 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 14:50:08,406 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 14:50:08,406 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 14:50:08,406 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 14:50:08,406 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.202 took 1.004934 seconds
2025-04-14 14:50:08,408 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.202
2025-04-14 14:50:09,412 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.202 took 1.003359 seconds
2025-04-14 14:50:09,414 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.202
2025-04-14 14:50:10,418 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.202 took 1.003758 seconds
2025-04-14 14:50:10,420 - cephci - ceph:1576 - INFO - Execute yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.142
2025-04-14 14:50:11,424 - cephci - ceph:1186 - DEBUG - Updating Subscription Management repositories.
2025-04-14 14:50:12,136 - cephci - ceph:1186 - DEBUG - 
2025-04-14 14:50:12,137 - cephci - ceph:1186 - DEBUG - This system has release set to 9.5 and it receives updates only for this release.
2025-04-14 14:50:12,137 - cephci - ceph:1186 - DEBUG - 
2025-04-14 14:50:12,942 - cephci - ceph:1186 - DEBUG - Last metadata expiration check: 1:07:47 ago on Mon Apr 14 13:42:05 2025.
2025-04-14 14:50:13,218 - cephci - ceph:1186 - DEBUG - Package python3-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 14:50:13,219 - cephci - ceph:1186 - DEBUG - Package python3-pip-21.3.1-1.el9.noarch is already installed.
2025-04-14 14:50:13,221 - cephci - ceph:1186 - DEBUG - Package fio-3.35-1.el9.x86_64 is already installed.
2025-04-14 14:50:13,222 - cephci - ceph:1186 - DEBUG - Package fuse-2.9.9-16.el9.x86_64 is already installed.
2025-04-14 14:50:13,223 - cephci - ceph:1186 - DEBUG - Package ceph-fuse-2:19.2.1-126.el9cp.x86_64 is already installed.
2025-04-14 14:50:13,224 - cephci - ceph:1186 - DEBUG - Package attr-2.5.1-3.el9.x86_64 is already installed.
2025-04-14 14:50:13,225 - cephci - ceph:1186 - DEBUG - Package gcc-11.5.0-5.el9_5.x86_64 is already installed.
2025-04-14 14:50:13,226 - cephci - ceph:1186 - DEBUG - Package python3-devel-3.9.21-1.el9_5.x86_64 is already installed.
2025-04-14 14:50:13,227 - cephci - ceph:1186 - DEBUG - Package git-2.43.5-2.el9_5.x86_64 is already installed.
2025-04-14 14:50:13,228 - cephci - ceph:1186 - DEBUG - Package lua-5.4.4-4.el9.x86_64 is already installed.
2025-04-14 14:50:13,327 - cephci - ceph:1186 - DEBUG - Dependencies resolved.
2025-04-14 14:50:13,328 - cephci - ceph:1186 - DEBUG - Nothing to do.
2025-04-14 14:50:13,328 - cephci - ceph:1186 - DEBUG - Complete!
2025-04-14 14:50:13,550 - cephci - ceph:1606 - INFO - Execution of yum install -y --nogpgcheck python3 python3-pip fio fuse ceph-fuse attr gcc python3-devel git lua on 10.0.195.142 took 3.129881 seconds
2025-04-14 14:50:13,592 - cephci - ceph:1576 - INFO - Execute pip3 install xattr numpy scipy on 10.0.195.142
2025-04-14 14:50:14,596 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: xattr in /usr/local/lib64/python3.9/site-packages (1.1.4)
2025-04-14 14:50:14,596 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: numpy in /usr/local/lib64/python3.9/site-packages (2.0.2)
2025-04-14 14:50:14,596 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: scipy in /usr/local/lib64/python3.9/site-packages (1.13.1)
2025-04-14 14:50:14,596 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib64/python3.9/site-packages (from xattr) (1.17.1)
2025-04-14 14:50:14,596 - cephci - ceph:1186 - DEBUG - Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.16.0->xattr) (2.22)
2025-04-14 14:50:14,596 - cephci - ceph:1186 - ERROR - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2025-04-14 14:50:14,597 - cephci - ceph:1606 - INFO - Execution of pip3 install xattr numpy scipy on 10.0.195.142 took 1.004479 seconds
2025-04-14 14:50:14,598 - cephci - ceph:1576 - INFO - Execute ls /home/cephuser on 10.0.195.142
2025-04-14 14:50:15,601 - cephci - ceph:1606 - INFO - Execution of ls /home/cephuser on 10.0.195.142 took 1.003227 seconds
2025-04-14 14:50:15,603 - cephci - ceph:1576 - INFO - Execute rpm -qa | grep -w 'dbench' on 10.0.195.142
2025-04-14 14:50:16,607 - cephci - ceph:1606 - INFO - Execution of rpm -qa | grep -w 'dbench' on 10.0.195.142 took 1.003941 seconds
2025-04-14 14:50:16,609 - cephci - ceph:1576 - INFO - Execute ceph fs ls --format json-pretty on 10.0.195.251
2025-04-14 14:50:17,614 - cephci - ceph:1606 - INFO - Execution of ceph fs ls --format json-pretty on 10.0.195.251 took 1.004152 seconds
2025-04-14 14:50:17,614 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 14:50:17,616 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251
2025-04-14 14:50:18,619 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251 took 1.003558 seconds
2025-04-14 14:50:18,621 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251
2025-04-14 14:50:19,625 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node8 on 10.0.195.251 took 1.003617 seconds
2025-04-14 14:50:19,627 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node8 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251
2025-04-14 14:50:20,630 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node8 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251 took 1.003442 seconds
2025-04-14 14:50:20,632 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251
2025-04-14 14:50:21,636 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node8.keyring on 10.0.195.251 took 1.003396 seconds
2025-04-14 14:50:21,636 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 14:50:21,638 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3
2025-04-14 14:50:22,641 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3 took 1.003268 seconds
2025-04-14 14:50:22,643 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3
2025-04-14 14:50:23,647 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node9 on 10.0.195.3 took 1.003428 seconds
2025-04-14 14:50:23,649 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node9 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3
2025-04-14 14:50:24,652 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node9 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3 took 1.003296 seconds
2025-04-14 14:50:24,654 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3
2025-04-14 14:50:25,658 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node9.keyring on 10.0.195.3 took 1.003266 seconds
2025-04-14 14:50:25,658 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 14:50:25,660 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202
2025-04-14 14:50:26,664 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202 took 1.003887 seconds
2025-04-14 14:50:26,666 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202
2025-04-14 14:50:27,669 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node10 on 10.0.195.202 took 1.003233 seconds
2025-04-14 14:50:27,671 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node10 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202
2025-04-14 14:50:28,675 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node10 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202 took 1.003194 seconds
2025-04-14 14:50:28,676 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202
2025-04-14 14:50:29,680 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node10.keyring on 10.0.195.202 took 1.003602 seconds
2025-04-14 14:50:29,681 - cephci - cephfs_utilsV1:729 - INFO - Giving required permissions for clients:
2025-04-14 14:50:29,683 - cephci - ceph:1576 - INFO - Execute ceph auth get client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142
2025-04-14 14:50:30,687 - cephci - ceph:1606 - INFO - Execution of ceph auth get client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142 took 1.003282 seconds
2025-04-14 14:50:30,688 - cephci - ceph:1576 - INFO - Execute ceph auth del client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142
2025-04-14 14:50:31,693 - cephci - ceph:1606 - INFO - Execution of ceph auth del client.ceph-regression-vhr823-futhjo-node11 on 10.0.195.142 took 1.003838 seconds
2025-04-14 14:50:31,694 - cephci - ceph:1576 - INFO - Execute ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node11 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142
2025-04-14 14:50:32,699 - cephci - ceph:1606 - INFO - Execution of ceph auth get-or-create client.ceph-regression-vhr823-futhjo-node11 mon 'allow *' mds 'allow *, allow * path=/' osd 'allow *' -o /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142 took 1.004548 seconds
2025-04-14 14:50:32,701 - cephci - ceph:1576 - INFO - Execute chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142
2025-04-14 14:50:33,706 - cephci - ceph:1606 - INFO - Execution of chmod 644 /etc/ceph/ceph.client.ceph-regression-vhr823-futhjo-node11.keyring on 10.0.195.142 took 1.004067 seconds
2025-04-14 14:50:33,709 - cephci - ceph:1576 - INFO - Execute ceph nfs cluster create cephfs-nfs ceph-regression-vhr823-futhjo-node7 on 10.0.195.251
2025-04-14 14:50:34,713 - cephci - ceph:1606 - INFO - Execution of ceph nfs cluster create cephfs-nfs ceph-regression-vhr823-futhjo-node7 on 10.0.195.251 took 1.00357 seconds
2025-04-14 14:50:34,713 - cephci - cephfs_volume_management:23 - INFO - Wait for the process to start or stop
2025-04-14 14:50:34,715 - cephci - ceph:1576 - INFO - Execute ceph orch ps | grep cephfs-nfs on 10.0.195.251
2025-04-14 14:50:35,718 - cephci - ceph:1606 - INFO - Execution of ceph orch ps | grep cephfs-nfs on 10.0.195.251 took 1.00355 seconds
2025-04-14 14:50:35,720 - cephci - ceph:1576 - INFO - Execute ceph nfs cluster ls -f json on 10.0.195.251
2025-04-14 14:50:36,724 - cephci - ceph:1606 - INFO - Execution of ceph nfs cluster ls -f json on 10.0.195.251 took 1.003851 seconds
2025-04-14 14:50:36,725 - cephci - zip_unzip_files_nfs:69 - INFO - ceph nfs cluster created successfully
2025-04-14 14:50:36,727 - cephci - ceph:1576 - INFO - Execute ceph fs ls --format json-pretty on 10.0.195.251
2025-04-14 14:50:37,731 - cephci - ceph:1606 - INFO - Execution of ceph fs ls --format json-pretty on 10.0.195.251 took 1.003671 seconds
2025-04-14 14:50:37,733 - cephci - ceph:1576 - INFO - Execute ceph nfs export create cephfs cephfs-nfs /export_099 cephfs path=/ on 10.0.195.251
2025-04-14 14:50:39,738 - cephci - ceph:1606 - INFO - Execution of ceph nfs export create cephfs cephfs-nfs /export_099 cephfs path=/ on 10.0.195.251 took 2.004556 seconds
2025-04-14 14:50:39,739 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_OTK9E on 10.0.195.251
2025-04-14 14:50:40,743 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_OTK9E on 10.0.195.251 took 1.003405 seconds
2025-04-14 14:50:40,744 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_099 /mnt/nfs_OTK9E on 10.0.195.251
2025-04-14 14:52:45,876 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_099 /mnt/nfs_OTK9E on 10.0.195.251 took 125.131753 seconds
2025-04-14 14:52:45,877 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_099 /mnt/nfs_OTK9E returned mount.nfs: Connection refused
 and code 32 on 10.0.195.251, Retrying in 60 seconds...
2025-04-14 14:53:45,939 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_OTK9E on 10.0.195.251
2025-04-14 14:53:46,944 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_OTK9E on 10.0.195.251 took 1.005001 seconds
2025-04-14 14:53:46,946 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_099 /mnt/nfs_OTK9E on 10.0.195.251
2025-04-14 14:55:52,080 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_099 /mnt/nfs_OTK9E on 10.0.195.251 took 125.133214 seconds
2025-04-14 14:55:52,080 - cephci - retry:28 - WARNING - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_099 /mnt/nfs_OTK9E returned mount.nfs: Connection refused
 and code 32 on 10.0.195.251, Retrying in 120 seconds...
2025-04-14 14:57:52,169 - cephci - ceph:1576 - INFO - Execute mkdir -p /mnt/nfs_OTK9E on 10.0.195.251
2025-04-14 14:57:53,175 - cephci - ceph:1606 - INFO - Execution of mkdir -p /mnt/nfs_OTK9E on 10.0.195.251 took 1.006376 seconds
2025-04-14 14:57:53,177 - cephci - ceph:1576 - INFO - Execute mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_099 /mnt/nfs_OTK9E on 10.0.195.251
2025-04-14 14:59:58,310 - cephci - ceph:1606 - INFO - Execution of mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_099 /mnt/nfs_OTK9E on 10.0.195.251 took 125.132582 seconds
2025-04-14 14:59:58,311 - cephci - zip_unzip_files_nfs:188 - INFO - mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_099 /mnt/nfs_OTK9E returned mount.nfs: Connection refused
 and code 32 on 10.0.195.251
2025-04-14 14:59:58,311 - cephci - zip_unzip_files_nfs:189 - INFO - Traceback (most recent call last):
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_nfs/zip_unzip_files_nfs.py", line 96, in run
    rc = fs_util.cephfs_nfs_mount(
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/utility/retry.py", line 32, in f_retry
    return f(*args, **kwargs)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_utilsV1.py", line 3277, in cephfs_nfs_mount
    client.exec_command(sudo=True, cmd=command)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 2305, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 1700, in exec_command
    raise CommandFailed(
ceph.ceph.CommandFailed: mount -t nfs -o port=2049 ceph-regression-vhr823-futhjo-node7:/export_099 /mnt/nfs_OTK9E returned mount.nfs: Connection refused
 and code 32 on 10.0.195.251

2025-04-14 14:59:58,311 - cephci - zip_unzip_files_nfs:192 - INFO - Cleaning up the system
2025-04-14 14:59:58,312 - cephci - ceph:1576 - INFO - Execute rm -rf /mnt/nfs_OTK9E/* on 10.0.195.251
2025-04-14 14:59:59,316 - cephci - ceph:1606 - INFO - Execution of rm -rf /mnt/nfs_OTK9E/* on 10.0.195.251 took 1.003362 seconds
2025-04-14 14:59:59,317 - cephci - ceph:1576 - INFO - Execute umount /mnt/nfs_OTK9E on 10.0.195.251
2025-04-14 15:00:00,321 - cephci - ceph:1606 - INFO - Execution of umount /mnt/nfs_OTK9E on 10.0.195.251 took 1.003591 seconds
2025-04-14 15:00:00,322 - cephci - run:854 - ERROR - umount /mnt/nfs_OTK9E returned umount: /mnt/nfs_OTK9E: not mounted.
 and code 32 on 10.0.195.251
Traceback (most recent call last):
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/run.py", line 839, in run
    rc = test_mod.run(
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_nfs/zip_unzip_files_nfs.py", line 199, in run
    client1.exec_command(sudo=True, cmd=command)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 2305, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/ceph/ceph.py", line 1700, in exec_command
    raise CommandFailed(
ceph.ceph.CommandFailed: umount /mnt/nfs_OTK9E returned umount: /mnt/nfs_OTK9E: not mounted.
 and code 32 on 10.0.195.251
2025-04-14 15:00:00,323 - cephci - ceph:1576 - INFO - Execute podman --version | awk {'print $3'} on 10.0.195.21
2025-04-14 15:00:01,327 - cephci - ceph:1606 - INFO - Execution of podman --version | awk {'print $3'} on 10.0.195.21 took 1.003643 seconds
2025-04-14 15:00:01,328 - cephci - run:1065 - INFO - Podman Version 5.2.2
2025-04-14 15:00:01,329 - cephci - ceph:1576 - INFO - Execute docker --version | awk {'print $3'} on 10.0.195.21
2025-04-14 15:00:02,332 - cephci - ceph:1606 - INFO - Execution of docker --version | awk {'print $3'} on 10.0.195.21 took 1.003168 seconds
2025-04-14 15:00:02,334 - cephci - ceph:1576 - INFO - Execute ceph --version | awk '{print $3}' on 10.0.195.251
2025-04-14 15:00:03,338 - cephci - ceph:1606 - INFO - Execution of ceph --version | awk '{print $3}' on 10.0.195.251 took 1.003412 seconds
2025-04-14 15:00:03,338 - cephci - run:1081 - INFO - ceph Version 19.2.1-126.el9cp
2025-04-14 15:00:03,339 - cephci - run:1040 - INFO - ceph_clusters_file rerun/regression-vHr823-FUTHJO
2025-04-14 15:00:03,340 - cephci - run:927 - INFO - Test <module 'cephfs_nfs.zip_unzip_files_nfs' from '/home/jenkins/ceph-builds/openstack/IBM/8.1/rhel-9/Regression/19.2.1-126/cephfs/99/cephci/tests/cephfs/cephfs_nfs/zip_unzip_files_nfs.py'> failed
